/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as TechnicianSearchIndexRouteImport } from './routes/technician-search.index'
import { Route as TechnicianProfilesIndexRouteImport } from './routes/technician-profiles.index'
import { Route as TechnicianCatalogsIndexRouteImport } from './routes/technician-catalogs.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OperationsIndexRouteImport } from './routes/operations.index'
import { Route as ClientProfilesIndexRouteImport } from './routes/client-profiles.index'
import { Route as ChatsIndexRouteImport } from './routes/chats.index'
import { Route as ActivityEventsIndexRouteImport } from './routes/activity-events.index'
import { Route as TechniciansTechnicianIdRouteImport } from './routes/technicians.$technicianId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as OperationsOperationIdRouteImport } from './routes/operations.$operationId'
import { Route as DevSupabaseRouteImport } from './routes/dev.supabase'
import { Route as ClientProfilesClientProfileIdRouteImport } from './routes/client-profiles.$clientProfileId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianSearchIndexRoute = TechnicianSearchIndexRouteImport.update({
  id: '/technician-search/',
  path: '/technician-search/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianProfilesIndexRoute = TechnicianProfilesIndexRouteImport.update({
  id: '/technician-profiles/',
  path: '/technician-profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianCatalogsIndexRoute = TechnicianCatalogsIndexRouteImport.update({
  id: '/technician-catalogs/',
  path: '/technician-catalogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsIndexRoute = OperationsIndexRouteImport.update({
  id: '/operations/',
  path: '/operations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProfilesIndexRoute = ClientProfilesIndexRouteImport.update({
  id: '/client-profiles/',
  path: '/client-profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityEventsIndexRoute = ActivityEventsIndexRouteImport.update({
  id: '/activity-events/',
  path: '/activity-events/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansTechnicianIdRoute = TechniciansTechnicianIdRouteImport.update({
  id: '/technicians/$technicianId',
  path: '/technicians/$technicianId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsOperationIdRoute = OperationsOperationIdRouteImport.update({
  id: '/operations/$operationId',
  path: '/operations/$operationId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSupabaseRoute = DevSupabaseRouteImport.update({
  id: '/dev/supabase',
  path: '/dev/supabase',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProfilesClientProfileIdRoute =
  ClientProfilesClientProfileIdRouteImport.update({
    id: '/client-profiles/$clientProfileId',
    path: '/client-profiles/$clientProfileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/client-profiles/$clientProfileId': typeof ClientProfilesClientProfileIdRoute
  '/dev/supabase': typeof DevSupabaseRoute
  '/operations/$operationId': typeof OperationsOperationIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/technicians/$technicianId': typeof TechniciansTechnicianIdRoute
  '/activity-events/': typeof ActivityEventsIndexRoute
  '/chats/': typeof ChatsIndexRoute
  '/client-profiles/': typeof ClientProfilesIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/technician-catalogs/': typeof TechnicianCatalogsIndexRoute
  '/technician-profiles/': typeof TechnicianProfilesIndexRoute
  '/technician-search/': typeof TechnicianSearchIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/client-profiles/$clientProfileId': typeof ClientProfilesClientProfileIdRoute
  '/dev/supabase': typeof DevSupabaseRoute
  '/operations/$operationId': typeof OperationsOperationIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/technicians/$technicianId': typeof TechniciansTechnicianIdRoute
  '/activity-events': typeof ActivityEventsIndexRoute
  '/chats': typeof ChatsIndexRoute
  '/client-profiles': typeof ClientProfilesIndexRoute
  '/operations': typeof OperationsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/technician-catalogs': typeof TechnicianCatalogsIndexRoute
  '/technician-profiles': typeof TechnicianProfilesIndexRoute
  '/technician-search': typeof TechnicianSearchIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/client-profiles/$clientProfileId': typeof ClientProfilesClientProfileIdRoute
  '/dev/supabase': typeof DevSupabaseRoute
  '/operations/$operationId': typeof OperationsOperationIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/technicians/$technicianId': typeof TechniciansTechnicianIdRoute
  '/activity-events/': typeof ActivityEventsIndexRoute
  '/chats/': typeof ChatsIndexRoute
  '/client-profiles/': typeof ClientProfilesIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/technician-catalogs/': typeof TechnicianCatalogsIndexRoute
  '/technician-profiles/': typeof TechnicianProfilesIndexRoute
  '/technician-search/': typeof TechnicianSearchIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/client-profiles/$clientProfileId'
    | '/dev/supabase'
    | '/operations/$operationId'
    | '/orders/$orderId'
    | '/technicians/$technicianId'
    | '/activity-events/'
    | '/chats/'
    | '/client-profiles/'
    | '/operations/'
    | '/orders/'
    | '/technician-catalogs/'
    | '/technician-profiles/'
    | '/technician-search/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/client-profiles/$clientProfileId'
    | '/dev/supabase'
    | '/operations/$operationId'
    | '/orders/$orderId'
    | '/technicians/$technicianId'
    | '/activity-events'
    | '/chats'
    | '/client-profiles'
    | '/operations'
    | '/orders'
    | '/technician-catalogs'
    | '/technician-profiles'
    | '/technician-search'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/client-profiles/$clientProfileId'
    | '/dev/supabase'
    | '/operations/$operationId'
    | '/orders/$orderId'
    | '/technicians/$technicianId'
    | '/activity-events/'
    | '/chats/'
    | '/client-profiles/'
    | '/operations/'
    | '/orders/'
    | '/technician-catalogs/'
    | '/technician-profiles/'
    | '/technician-search/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ClientProfilesClientProfileIdRoute: typeof ClientProfilesClientProfileIdRoute
  DevSupabaseRoute: typeof DevSupabaseRoute
  OperationsOperationIdRoute: typeof OperationsOperationIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  TechniciansTechnicianIdRoute: typeof TechniciansTechnicianIdRoute
  ActivityEventsIndexRoute: typeof ActivityEventsIndexRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
  ClientProfilesIndexRoute: typeof ClientProfilesIndexRoute
  OperationsIndexRoute: typeof OperationsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  TechnicianCatalogsIndexRoute: typeof TechnicianCatalogsIndexRoute
  TechnicianProfilesIndexRoute: typeof TechnicianProfilesIndexRoute
  TechnicianSearchIndexRoute: typeof TechnicianSearchIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician-search/': {
      id: '/technician-search/'
      path: '/technician-search'
      fullPath: '/technician-search/'
      preLoaderRoute: typeof TechnicianSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician-profiles/': {
      id: '/technician-profiles/'
      path: '/technician-profiles'
      fullPath: '/technician-profiles/'
      preLoaderRoute: typeof TechnicianProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician-catalogs/': {
      id: '/technician-catalogs/'
      path: '/technician-catalogs'
      fullPath: '/technician-catalogs/'
      preLoaderRoute: typeof TechnicianCatalogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/': {
      id: '/operations/'
      path: '/operations'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-profiles/': {
      id: '/client-profiles/'
      path: '/client-profiles'
      fullPath: '/client-profiles/'
      preLoaderRoute: typeof ClientProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-events/': {
      id: '/activity-events/'
      path: '/activity-events'
      fullPath: '/activity-events/'
      preLoaderRoute: typeof ActivityEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians/$technicianId': {
      id: '/technicians/$technicianId'
      path: '/technicians/$technicianId'
      fullPath: '/technicians/$technicianId'
      preLoaderRoute: typeof TechniciansTechnicianIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/$operationId': {
      id: '/operations/$operationId'
      path: '/operations/$operationId'
      fullPath: '/operations/$operationId'
      preLoaderRoute: typeof OperationsOperationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/supabase': {
      id: '/dev/supabase'
      path: '/dev/supabase'
      fullPath: '/dev/supabase'
      preLoaderRoute: typeof DevSupabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-profiles/$clientProfileId': {
      id: '/client-profiles/$clientProfileId'
      path: '/client-profiles/$clientProfileId'
      fullPath: '/client-profiles/$clientProfileId'
      preLoaderRoute: typeof ClientProfilesClientProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ClientProfilesClientProfileIdRoute: ClientProfilesClientProfileIdRoute,
  DevSupabaseRoute: DevSupabaseRoute,
  OperationsOperationIdRoute: OperationsOperationIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  TechniciansTechnicianIdRoute: TechniciansTechnicianIdRoute,
  ActivityEventsIndexRoute: ActivityEventsIndexRoute,
  ChatsIndexRoute: ChatsIndexRoute,
  ClientProfilesIndexRoute: ClientProfilesIndexRoute,
  OperationsIndexRoute: OperationsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  TechnicianCatalogsIndexRoute: TechnicianCatalogsIndexRoute,
  TechnicianProfilesIndexRoute: TechnicianProfilesIndexRoute,
  TechnicianSearchIndexRoute: TechnicianSearchIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
